- name: ec2 creation and route53 upgradation
  hosts: localhost
  connection: local
  vars:
   AMI_ID: "ami-09c813fb71547fc4f"
   SG_ID: "sg-00fa736b2eba8959d"
   ZONE_ID: "Z05445223EGIS9AWDWK63"
   DOMAIN_NAME: "prudhvii.fun"
   instances:
   - mysql
  tasks: 
   - name: ec2 creation
     amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ SG_ID }}"
      image_id: "{{ AMI_ID }}"
     loop: "{{ instances }}"
     register: ec2_output
    
  #  - name: printing ec2 output
  #    ansible.builtin.debug:
  #       msg: "{{ ec2_output }}" 
    
  #  - name: print public ipaddress
  #    ansible.builtin.debug:
  #       msg: "{{ item.instances[0].public_ip_address }}"
  #    loop: "{{ ec2_output.results }}"

  #  - name: print private ipaddress
  #    ansible.builtin.debug:
  #       msg: "{{ item.instances[0].private_ip_address }}"
  #    loop: "{{ ec2_output.results }}"

   - name: Add new.example.com as an A record
     amazon.aws.route53:
        state: present
        zone: "{{ DOMAIN_NAME }}" # Replace with your hosted zone name
        record: "{{ item.item }}.{{ DOMAIN_NAME }}" #mysql.prudhvii.fun
        type: A
        ttl: 1 # Time To Live in seconds
        value: "{{ item.instances[0].private_ip_address }}" # Replace with the target IPv4 address
        overwrite: true
     loop: "{{ ec2_output.results }}"